accepted = [
    # Source code licenses.
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "MIT",
    "Unicode-DFS-2016",
    "Zlib",
    # Font licenses.
    "OFL-1.1",
    "LicenseRef-UFL-1.0",
]
